name: Build macOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build AI Notizassistent
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
          xcodebuild -version
      
      - name: Check Project Configuration
        run: |
          cd AINotizassistent
          echo "=== XCODEBUILD LIST ==="
          xcodebuild -list -project AINotizassistent.xcodeproj
          echo ""
          echo "=== AVAILABLE SCHEMES ==="
          xcodebuild -listSchemes -project AINotizassistent.xcodeproj
      
      - name: Clean Build
        run: |
          cd AINotizassistent
          xcodebuild clean -project AINotizassistent.xcodeproj -scheme AINotizassistent
      
      - name: Build App
        run: |
          cd AINotizassistent
          xcodebuild build \
            -project AINotizassistent.xcodeproj \
            -scheme AINotizassistent \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Check Build Result
        run: |
          cd AINotizassistent
          echo "Search for built app..."
          find . -name "*.app" -type d || echo "No app found"
          ls -la DerivedData/Build/Products/Debug/ 2>/dev/null || echo "No Debug output"
